<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Payroll App')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
    ?>
</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <!-- Navigation bar -->
                <?php
                // Initialize navbar items
                $this->mainMenu()->setItems([
                    [
                        'id' => 'home',
                        'label' => 'App HOME',
                        'link' => $this->url('home')
                    ],
                ]);

                // Check if the activeMenuItemId passed to layout view model
                // and if so, use it for setting active navbar item.
                if (isset($activeMenuItemId)) {
                    $this->mainMenu()->setActiveItemId($activeMenuItemId);
                }

                // Render the navbar
                echo $this->mainMenu()->render();
                ?>
            </div>
        </div>


    <div class="row">
        <div class="col-md-12">
            <!-- Page content placeholder -->
            <?= $this->content; ?>
        </div>
    </div>
    <hr>
    <div class="row">
        <footer>
            <p>&copy; <?= date('Y') ?>.</p>
        </footer>
    </div>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
